// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef PROYECTO1_H
#define PROYECTO1_H

#include <ngrest/common/Service.h>
#include <string>
#include "list.h"

class practica1: public ngrest::Service
{
public:

    // *method: POST
   // *location: /newProfessor
   std::string newProfessor(const Data& data);

    // *method: POST
   // *location: /newCourse
   std::string newCourse(const curso& data);

    // *method: POST
   // *location: /newSalon
   std::string newSalon(const salData& data);

   // *method: GET
   // *location: /getMaestros
   std::list<Data> getMaestros();

    // *method: GET
   // *location: /getEdificios
   std::list<Data> getEdificios();


   // *method: POST
   // *location: /getGraphic
   std::string getGraphic(const std::string& choice);

};


#endif // PROYECTO1_H
