// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef PROYECTO1_H
#define PROYECTO1_H

#include <ngrest/common/Service.h>
#include <string>
#include "list.h"

class practica1: public ngrest::Service
{
public:

    // *method: POST
   // *location: /newProfessor
   std::string newProfessor(const Data& data);

    // *method: POST
   // *location: /newCourse
   std::string newCourse(const curso& data);

    // *method: POST
   // *location: /newSalon
   std::string newSalon(const salData& data);

    // *method: POST
   // *location: /deleteProfessor
   std::string deleteProfessor(const std::string& id);

   // *method: POST
   // *location: /deleteCourse
   std::string deleteCourse(const std::string& id);

   // *method: POST
   // *location: /modifyProfessor
   std::string modifyProfessor(const std::string& id, const Data& data);

   // *method: POST
   // *location: /modifyCourse
   std::string modifyCourse(const std::string& id, const Data& data);

   // *method: GET
   // *location: /getMaestros
   std::list<Data> getMaestros();

    // *method: GET
   // *location: /getCursos
   std::list<Data> getCursos();

    // *method: GET
   // *location: /getEdificios
   std::list<deuxData> getEdificios();

    // *method: GET
   // *location: /getReport
   std::list<std::string> getReport();

   // *method: POST
   // *location: /getGraphic
   std::string getGraphic(const std::string& choice);

};


#endif // PROYECTO1_H
